// Llista curada dels carrets més habituals, amb la seva ISO nativa (de caixa).
// No cal que sigui exhaustiva: l'usuari sempre pot escriure'n un altre nom a mà.
const FILM_STOCKS = [
  { nom: 'Kodak Portra 160', iso: 160, tipus: 'color' },
  { nom: 'Kodak Portra 400', iso: 400, tipus: 'color' },
  { nom: 'Kodak Portra 800', iso: 800, tipus: 'color' },
  { nom: 'Kodak Gold 200', iso: 200, tipus: 'color' },
  { nom: 'Kodak ColorPlus 200', iso: 200, tipus: 'color' },
  { nom: 'Kodak Ultramax 400', iso: 400, tipus: 'color' },
  { nom: 'Kodak Ektar 100', iso: 100, tipus: 'color' },
  { nom: 'Kodak Tri-X 400', iso: 400, tipus: 'bn' },
  { nom: 'Kodak T-Max 100', iso: 100, tipus: 'bn' },
  { nom: 'Kodak T-Max 400', iso: 400, tipus: 'bn' },
  { nom: 'Kodak ProImage 100', iso: 100, tipus: 'color' },
  { nom: 'Kodak Vision3 250D', iso: 250, tipus: 'color' },
  { nom: 'Kodak Vision3 500T', iso: 500, tipus: 'color' },
  { nom: 'Fujifilm Superia X-TRA 400', iso: 400, tipus: 'color' },
  { nom: 'Fujifilm 200', iso: 200, tipus: 'color' },
  { nom: 'Fujifilm Pro 400H', iso: 400, tipus: 'color' },
  { nom: 'Fujifilm Provia 100F', iso: 100, tipus: 'color' },
  { nom: 'Fujifilm Velvia 50', iso: 50, tipus: 'color' },
  { nom: 'Fujifilm Velvia 100', iso: 100, tipus: 'color' },
  { nom: 'Fujifilm Acros 100 II', iso: 100, tipus: 'bn' },
  { nom: 'Ilford HP5 Plus 400', iso: 400, tipus: 'bn' },
  { nom: 'Ilford FP4 Plus 125', iso: 125, tipus: 'bn' },
  { nom: 'Ilford Delta 100', iso: 100, tipus: 'bn' },
  { nom: 'Ilford Delta 400', iso: 400, tipus: 'bn' },
  { nom: 'Ilford Delta 3200', iso: 3200, tipus: 'bn' },
  { nom: 'Ilford Pan F Plus 50', iso: 50, tipus: 'bn' },
  { nom: 'Ilford XP2 Super 400', iso: 400, tipus: 'bn' },
  { nom: 'Ilford Ortho Plus 80', iso: 80, tipus: 'bn' },
  { nom: 'CineStill 400D', iso: 400, tipus: 'color' },
  { nom: 'CineStill 800T', iso: 800, tipus: 'color' },
  { nom: 'CineStill BwXX', iso: 250, tipus: 'bn' },
  { nom: 'Lomography Color 100', iso: 100, tipus: 'color' },
  { nom: 'Lomography Color 400', iso: 400, tipus: 'color' },
  { nom: 'Lomography Color 800', iso: 800, tipus: 'color' },
  { nom: 'Lomography Lady Grey 400', iso: 400, tipus: 'bn' },
  { nom: 'Lomography Earl Grey 100', iso: 100, tipus: 'bn' },
  { nom: 'Agfaphoto APX 100', iso: 100, tipus: 'bn' },
  { nom: 'Agfaphoto APX 400', iso: 400, tipus: 'bn' },
  { nom: 'Rollei RPX 25', iso: 25, tipus: 'bn' },
  { nom: 'Rollei RPX 100', iso: 100, tipus: 'bn' },
  { nom: 'Rollei RPX 400', iso: 400, tipus: 'bn' },
  { nom: 'Kentmere Pan 100', iso: 100, tipus: 'bn' },
  { nom: 'Kentmere Pan 400', iso: 400, tipus: 'bn' },
  { nom: 'Polaroid Color 600', iso: 640, tipus: 'color' },
  { nom: 'Polaroid B&W 600', iso: 640, tipus: 'bn' },
  { nom: 'Fomapan 100', iso: 100, tipus: 'bn' },
  { nom: 'Fomapan 400', iso: 400, tipus: 'bn' },
  { nom: 'JCH StreetPan 400', iso: 400, tipus: 'bn' },
  { nom: 'Adox CHS 100 II', iso: 100, tipus: 'bn' },
  { nom: 'Adox Silvermax', iso: 100, tipus: 'bn' }
];

function trobarFilmStock(nom) {
  if (!nom) return null;
  const net = nom.trim().toLowerCase();
  return FILM_STOCKS.find(f => f.nom.toLowerCase() === net) || null;
}
